include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes