// Mocks generated by Mockito 5.4.2 from annotations
// in cg_apparel/test/domain/usecases/place_order_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cg_apparel/core/error/failures.dart' as _i5;
import 'package:cg_apparel/domain/entities/cart.dart' as _i7;
import 'package:cg_apparel/domain/entities/order.dart' as _i6;
import 'package:cg_apparel/domain/repositories/order_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i3.OrderRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Order>>> getOrders(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Order>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Order>>(
          this,
          Invocation.method(
            #getOrders,
            [userId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Order>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Order>>(
          this,
          Invocation.method(
            #getOrders,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Order>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> placeOrder(_i7.Cart? cart) =>
      (super.noSuchMethod(
        Invocation.method(
          #placeOrder,
          [cart],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #placeOrder,
            [cart],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #placeOrder,
            [cart],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
